### ISSUE TITLE
new_stack() function returns Vec<Char> instead Vec<String> in Latest Rust Versions

### ISSUE THREAD

**Issue by pAkalpa** [PacktPublishing/Rust-Programming-Master-Class-from-Beginner-to-Expert#1]
https://github.com/PacktPublishing/Rust-Programming-Master-Class-from-Beginner-to-Expert/blob/499b7748f314b9423539926f84d1bd599fb04a89/4-1%20Project-Stack%20Implemenation%20and%20Applications/5%20-%206%20-%207%20%20Expression%20Evaluation%20(Rust%20Implementation%20using%20Stacks).txt#L86

**Comment by Sonakshis** [comment]
Hi, 
We are currently working on updating this course. The updated course should be live soon.
