### ISSUE TITLE
Student problems

### ISSUE THREAD

**Issue by timrichardson** [PacktPublishing/Rust-Programming-Master-Class-from-Beginner-to-Expert#2]
Hi, 
I am following this course using my O'Reilly subscription. 
At the end of the the video "Ownership and References in Functions" there is reference to student exercises.
But where are they?

**Comment by Sonakshis** [comment]
Hi
All six practice questions referred to in the course are available under the "Practice Questions" folder on GitHub for the students to practice their skills.

GitHub repo path: https://github.com/PacktPublishing/Rust-Programming-Master-Class-from-Beginner-to-Expert/tree/main/Practice%20Questions
