### ISSUE TITLE
Error in Postfix Expression in Video 5.3

### ISSUE THREAD

**Issue by JuanCab** [PacktPublishing/Rust-Programming-Master-Class-from-Beginner-to-Expert#3]
I tried to submit an Errata through the website but could not.  The professor makes an error at the very end of video5_3 where he is working through converting and expression from infix to postfix, the final expression should be
`33, 45, 3, /, 2, 9, +, *, +, 50, -` 
instead of 
`33, 45, 3, /, 2, 9, +, *, +, -`.
He completely skipped over the final operand of 50.  The professor does have the correct expression in video5_4, but missed this error in video5_3.

**Comment by Sonakshis** [comment]
Hi,

Thank you so much for bringing this to our attention. We appreciate your feedback! Yes, that has been mistakenly left over. We have made a note of the error and informed the author about it. We will make sure that this is corrected in future releases.  

We have published an update to the course this month, so it will be helpful if you check out for the latest updates on our channel - https://www.packtpub.com/product/rust-programming-masterclass-from-beginner-to-expert-video/9781804612187

Happy learning!
